/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface': '#131313',
        'surface-dim': '#131313',
        'surface-bright': '#3a3939',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-low': '#1c1b1b',
        'surface-container': '#201f1f',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353534',
        'surface-variant': '#353534',
        'surface-tint': '#e9c349',
        'on-surface': '#e5e2e1',
        'on-surface-variant': '#d0c5af',
        'inverse-surface': '#e5e2e1',
        'inverse-on-surface': '#313030',
        'background': '#131313',
        'on-background': '#e5e2e1',
        'outline': '#99907c',
        'outline-variant': '#4d4635',

        'primary': '#f2ca50',
        'on-primary': '#3c2f00',
        'primary-container': '#d4af37',
        'on-primary-container': '#554300',
        'inverse-primary': '#735c00',
        'primary-fixed': '#ffe088',
        'primary-fixed-dim': '#e9c349',
        'on-primary-fixed': '#241a00',
        'on-primary-fixed-variant': '#574500',

        'secondary': '#c6c7c2',
        'on-secondary': '#2f312e',
        'secondary-container': '#484a46',
        'on-secondary-container': '#b8b9b4',
        'secondary-fixed': '#e3e3de',
        'secondary-fixed-dim': '#c6c7c2',
        'on-secondary-fixed': '#1a1c19',
        'on-secondary-fixed-variant': '#454744',

        'tertiary': '#d0cdcd',
        'on-tertiary': '#313030',
        'tertiary-container': '#b4b2b2',
        'on-tertiary-container': '#454544',
        'tertiary-fixed': '#e5e2e1',
        'tertiary-fixed-dim': '#c8c6c5',
        'on-tertiary-fixed': '#1c1b1b',
        'on-tertiary-fixed-variant': '#474746',

        'error': '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
      },
      borderRadius: {
        'none': '0px',
        'DEFAULT': '0px',
        'sm': '0px',
        'md': '0px',
        'lg': '0px',
        'xl': '0px',
        '2xl': '0px',
        '3xl': '0px',
        'full': '9999px',
      },
      spacing: {
        'unit': '8px',
        'gutter': '24px',
        'margin-desktop': '80px',
        'margin-mobile': '24px',
        'section-gap': '160px',
      },
      fontFamily: {
        'brand': ['"Cinzel Decorative"', '"Playfair Display"', 'serif'],
        'headline': ['"Playfair Display"', 'serif'],
        'body': ['Montserrat', 'sans-serif'],
        'display-lg': ['"Playfair Display"', 'serif'],
        'display-lg-mobile': ['"Playfair Display"', 'serif'],
        'headline-lg': ['"Playfair Display"', 'serif'],
        'headline-md': ['"Playfair Display"', 'serif'],
        'body-lg': ['Montserrat', 'sans-serif'],
        'body-md': ['Montserrat', 'sans-serif'],
        'label-caps': ['Montserrat', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['84px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg-mobile': ['48px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-lg': ['48px', { lineHeight: '1.2', fontWeight: '600' }],
        'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.8', letterSpacing: '0.01em', fontWeight: '300' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1.0', letterSpacing: '0.2em', fontWeight: '600' }],
      },
      boxShadow: {
        'glass': '0 20px 40px rgba(0, 0, 0, 0.5)',
        'gold-glow': '0 0 15px rgba(212, 175, 55, 0.3)',
      },
    },
  },
  plugins: [],
};
